### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by CasLuBrOzMaster** [CasLuBrOz/github-crash-course#1]
I think it looks better if the title is a bit more blue.

The styling rule could be chaned like this:

```css
h1 {
  color: #69a2a8;
}
```
